import Head from "next/head";
import { Header } from "components/Header";
import { Footer } from "components/Footer";
import { Menu } from "components/Menu";

export function Layout({children}){
    return(
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Menu/>
                {/* <Header/> */}
                <main className="max-w-xl mx-auto p-5 pb-28">
                    {children}
                </main>
                {/* <Footer/> */}
            </div>
        </>
    )
}